class AssignUnassignPaths(object):
    def __init__(self):
        self.devices_menu_btn = 'data-testid=devices-nav-menu'
        self.search_field = 'data-testid=search-field'
        self.select_all_nth_btn = 'aria-label=select all'
        self.detach_subs_btn = 'data-testid=detach-subscription-btn'
        self.detach_btn = 'data-testid=detach-btn'
        self.close_btn = 'data-testid=close-btn'
        self.devices_btn = 'data-testid=devices-btn'
        self.apply_to_subs_btn = 'data-testid=apply-to-subscriptions-btn'
        self.apply_subs_btn = 'data-testid=apply-subscriptions-btn'
        self.lic_tier_dropdown = 'data-testid=license-tier-dropdown'
        self.apply_sub_btn = 'data-testid=apply-subscription-btn'
        self.click_finish = 'data-testid=button-finish'
        self.assigned_lic_summary = 'data-testid=text-assigned-licensed-tab-summary'
        self.select_all = '[aria-label=\"select all\"] div'
        self.action_btn = '[data-testid=\"bulk-actions\"] [aria-label=\"Open Drop\"]'
