"""
Activate Folder Rule object.
"""


class RuleData:
    def __init__(self):
        self.name = "auto rule"
        self.type = "Notification"
        self.folder = ""
        self.email_on = ""
        self.email_to = ""
        self.for_rule = ""
        self.prov_type = ""
        self.amp_ip = ""
        self.ap_group = ""
        self.shared_secret = ""
        self.organization = ""
        self.controller = ""
        self.conductor_mac = ""
        self.persist_ip = ""
        self.backup_contrlr_ip = ""
        self.primary_conductor = ""
        self.primary_ctrl_ip = ""
        self.backup_conductor = ""
        self.backup_ctrl_ip = ""
        self.branch_ctrl_group = ""
        self.redundancy_level = ""
        self.config_node_path = ""
        self.mobility_conductor = ""
        self.mobility_conductor_ip = ""
        self.backup_mobility_conductor = ""
        self.vpn_concentrator_mac = ""
        self.vpn_concentrator_ip = ""
        self.backup_vpn_concentrator_mac = ""
        self.country = ""
